# Generated by Django 2.2.4 on 2019-08-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190815_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Deposit', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Withdraw', to='users.Account'),
        ),
    ]
